### ISSUE TITLE
make install is not available

### ISSUE THREAD

**Issue by jan-koupil** [sndrsmnk/hid-philips-asus#1]
According to the readme, the **make install** command should be executed. However a 
`make: *** No rule to make target 'install'.  Stop.`
is received. 

It is possible to execute **make all** that runs. Though I am not sure if it does all expected things.

**Comment by sndrsmnk** [comment]
This github repo was reworked to be a 'DKMS'-package for Debian(-derivative) systems.

Running '_make all_' builds the kernel module, but does not install the resulting .ko file.
You might have to manually place _hid-philips-asus.ko_ in _/lib/modules/$(uname -r)/updates/_ and run _depmod -a_.
