### ISSUE TITLE
The buttons in bottom part of the IR do not work

### ISSUE THREAD

**Issue by jan-koupil** [sndrsmnk/hid-philips-asus#3]
When IRW is started, all keys are registered with the exception of the keys in the bootom part ("the circle and its center"). These do not produce any event.

I was using the old usb-hid-mapper : http://forum.kodi.tv/showthread.php?tid=88560, but it stopped working with the new kernels. With the old mapper I could get the key codes. According to my archive these were the codes (and my mappings):

```
02010000:KEY_MUTE
02000100:KEY_REWIND
02000002:KEY_PLAYPAUSE
02800000:KEY_FASTFORWARD
02400000:KEY_PREVIOUS
02000800:KEY_STOP
02200000:KEY_NEXT
02020000:KEY_VOLUMEUP
02040000:KEY_VOLUMEDOWN
030000000000010000:KEY_ESC
030000000020000000:KEY_KP1
030000000000040000:KEY_KP2
030000000000020000:KEY_KP3
030000000080000000:KEY_KP4
030000000040000000:KEY_KP5
030000000000008000:KEY_TAB
030010000000000000:KEY_MENU
```

Now all numeric codes are changed and the bottom are not present at all. Here are the same keypresses with todays configuration:

```
0001007100000001 00 KEY_MUTE devinput
000100a800000001 00 KEY_REWIND devinput
000100a400000001 00 KEY_PLAYPAUSE devinput
000100d000000001 00 KEY_FASTFORWARD devinput
000100a500000001 00 KEY_PREVIOUSSONG devinput
000100a600000001 00 KEY_STOPCD devinput
000100a300000001 00 KEY_NEXTSONG devinput
0001007300000001 00 KEY_VOLUMEUP devinput
0001007200000001 00 KEY_VOLUMEDOWN devinput
0001009e00000001 00 KEY_BACK devinput
… and missing 8 records.
```

**Comment by sndrsmnk** [comment]
The bottom half of the remote not working usually points to the 'mceusb' driver grabbing the device before hid_philips_asus can do so. Make sure you blacklist the 'mceusb' driver by deploying the _contrib/modprobe_d_hid-philips-asus.conf_ file to _/etc/modprobe.d/_ or whatever suits your distribution.

dmesg should show:

> philips_asus 0003:0471:206C.0003: input: USB HID v1.00 Keyboard [PHILIPS MCE USB IR Receiver- Spinel plusf0r ASUS] on usb-0000:00:04.0-3/input0

if it does, your remote might differ from mine and we might be looking at patching that. :)

**Comment by jan-koupil** [comment]
Thank you, you were right. On my ubuntu I had to blacklist the mceusb - manully by adding a line 
`blacklist mceusb`
to /etc/modprobe.d/blacklist.conf
Now is the remote working with all keys.
